### ISSUE TITLE
User share processing results with another user

### ISSUE THREAD

**Issue by rconway** [rconway/ractest#1]
As a user, I want to share my processing results with another user.

- [ ] fix problem - ref. rconway/deployment-guide#2
- [ ] do deploy - ref. rconway/deployment-guide#1
- [ ] rconway/deployment-guide#3
